### ISSUE TITLE
Invalid Swift Support when uploading to iTunes Connect

### ISSUE THREAD

**Issue by rhuariglen1** [xndrs/XReSign#1]
I received this email from Apple after a successful upload to the iTunes Connect. Any ideas on how to rectify this?

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "EdgevisTest". To process your delivery, the following issues must be corrected:
> 
> Invalid Swift Support - The file libswiftAVFoundation.dylib doesn’t have the correct code signature. Make sure you’re using the correct signature, rebuild your app using the current public (GM) version of Xcode, and resubmit it. Don’t just modify the code signature of libswiftAVFoundation.dylib.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

**Comment by xndrs** [comment]
It can be that you are trying to upload developer build as release. 
And one more moment: for release use XCode distribution process.
Any other script today is used for other purposes, like developer, ad-hoc or enterprise distribution. Use them for release is a bit strange.

**Comment by rhuariglen1** [comment]
Okay thank you.
