### ISSUE TITLE
Add the Gui app

### ISSUE THREAD

**Issue by Dershowitz011** [xndrs/XReSign#10]
For those who don't have Xcode, cannot build. Please add the GUI app ASAP. Thanks.

**Comment by xndrs** [comment]
> For those who don't have Xcode, cannot build. Please add the GUI app ASAP. Thanks.

There is a script: xresign.sh inside "Scripts" folder. You can run it from command line. No needs in Xcode.

**Comment by Dershowitz011** [comment]
The GUI app would be rally helpful. Do Oblige. Thanks.

**Comment by xndrs** [comment]
> The GUI app would be rally helpful. Do Oblige. Thanks.
Thanks for the note.
Added in 1.0.3 release

**Comment by xndrs** [comment]
> The GUI app would be rally helpful. Do Oblige. Thanks.

Thanks for the note. Added in 1.0.3 release.
