### ISSUE TITLE
how to change app name also of ipa during resigning

### ISSUE THREAD

**Issue by UmairShams** [xndrs/XReSign#11]
Hi there...
I wan to add new text field to change the app name of ipa. Please tell me how can i do it.
Thanks

**Comment by xndrs** [comment]
> Hi there...
> I wan to add new text field to change the app name of ipa. Please tell me how can i do it.
> Thanks

You are welcome to write such little project in your forked repository: add text field into the view controller, pass it value to sign script as additional parameter, change script to save signed file with user defined output path or name. You need to have a basic knowledge in Swift and Bash.

**Comment by UmairShams** [comment]
I am ios developer and but which parameter should i pass for changing app
name ?

**Comment by UmairShams** [comment]
What should be added in script ? kindly can you tell? actually i have  no much knowledge in script..

**Comment by Dershowitz011** [comment]
Using Plistbuddy in mac, change `CFBundleDisplayName`. This should be done in script.

**Comment by UmairShams** [comment]
Ok  Thanks

**Comment by UmairShams** [comment]
thanks for great help

**Comment by Dershowitz011** [comment]
Also, kindly add the GUI app with all updates. It's hard for people WITHOUT `X-code` to use the script.
