### ISSUE TITLE
Crash when finished on showing dialog

### ISSUE THREAD

**Issue by AccuPhoenix01** [xndrs/XReSign#12]
Running XRS, when process is complete:
`Fatal error: Unexpectedly found nil while unwrapping an Optional value`

in:
`private func showAlertWith(title: String?, message: String, style: NSAlert.Style) {`
on:
`alert.beginSheetModal(for: NSApp.keyWindow!, completionHandler: nil)`

I had the app in the background while I was doing something else. Resigned app was not saved, tmp file of 0kb is created. XCode 10.2.1 on Mojave.
(Resigned app has much different name than expected.)

![Screen Shot 2019-08-13 at 10 09 24 AM](https://user-images.githubusercontent.com/46455562/62948547-8da8f780-bdb2-11e9-8711-be663b6ccf92.png)

**Comment by xndrs** [comment]
Thanks a lot. Fixed in 1.0.3
