### ISSUE TITLE
codesign_allocate: file not in an order that can be processed (code signature data out of place):

### ISSUE THREAD

**Issue by ZanderZhang** [xndrs/XReSign#15]

**Comment by xndrs** [comment]
Are you trying to insert dylib into a Mach-O binary?

**Comment by ZanderZhang** [comment]
> Are you trying to insert dylib into a Mach-O binary?

no, resign only

**Comment by xndrs** [comment]
> > Are you trying to insert dylib into a Mach-O binary?
> 
> no, resign only

the place of the problem should be described in the text that follows the words "_(code signature data out of place):..._ ". You can understand which file creates a problem when signing.

**Comment by ZanderZhang** [comment]
thanks sir, would you have a look?
[http://tmp.link/f/5d7711528c1a4](url)

**Comment by xndrs** [comment]
> thanks sir, would you have a look?
> [http://

Hey. I believe you understand that this is not the best decision to share information through a temporary link to an unknown site... (( I suggest you add a log here that comes after the message: "_(code signature data out of place):_" Maybe some one can help you.
