### ISSUE TITLE
ipa file is not created

### ISSUE THREAD

**Issue by XMark4281** [xndrs/XReSign#2]
Hello, first of all, thank you for this code! I am trying to use the xresign.sh to sign an app but it has an issue. It seems to sign fine but the problem is that the ipa file is not created when finished and all of the contents are still in the tmp folder. Additionally it just stops and doe snot finish off with "Creating the signed ipa" and never mentions "XReSign FINISHED"

**Comment by xndrs** [comment]
If you run resign process from the program, the result is successful or not ?
Could you please write example of your command line ?
