### ISSUE TITLE
Catalina problem

### ISSUE THREAD

**Issue by NicolasVZ777** [xndrs/XReSign#20]
Since I have updated to Catalina, the app I resign cannot be installed. Anyone else experience this issue?

**Comment by zhaishuai** [comment]
My MacOS version is 10.15.3, I have the same problem with NicolasVZ777.

**Comment by xndrs** [comment]
> Since I have updated to Catalina, the app I resign cannot be installed. Anyone else experience this issue?

any error log? there is a script "xresign.sh" inside "scripts" folder to run from command line. may be there you'll see the error

**Comment by NicolasVZ777** [comment]
Here is the log generated by "xresign.sh" on macOS Catalina :

2020-02-24 17:45:03.128761+0800 XReSign[5842:243491] Metal API Validation Enabled
Start resign the app...
Coping provisioning profile into application payload
Extract entitlements from mobileprovisioning
Sign process using existing bundle identifier from payload
Get list of components and resign with certificate: Apple Development: Name (XXXXXXXXXXX)
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftObjectiveC.dylib: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftObjectiveC.dylib: the codesign_allocate helper tool cannot be found or used
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftCore.dylib: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftCore.dylib: the codesign_allocate helper tool cannot be found or used
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftCoreGraphics.dylib: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftCoreGraphics.dylib: the codesign_allocate helper tool cannot be found or used
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftDispatch.dylib: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftDispatch.dylib: the codesign_allocate helper tool cannot be found or used
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/INSSDK.framework: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/INSSDK.framework: the codesign_allocate helper tool cannot be found or used
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftCoreFoundation.dylib: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftCoreFoundation.dylib: the codesign_allocate helper tool cannot be found or used
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftDarwin.dylib: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftDarwin.dylib: the codesign_allocate helper tool cannot be found or used
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftFoundation.dylib: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app/Frameworks/libswiftFoundation.dylib: the codesign_allocate helper tool cannot be found or used
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/Nicolas/Desktop/Resign/tmp/app/Payload/APP.app: the codesign_allocate helper tool cannot be found or used
Creating the signed ipa
Clear temporary files
XReSign FINISHED

**Comment by xndrs** [comment]
> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
> 

That's a problem. It seems that your machine is missing for xcode developer tools.
Open Terminal, and run the following: 
`xcode-select --install`

You do not need Xcode, you can install only the Command Line Tools.

**Comment by NicolasVZ777** [comment]
It works now, that was the issue. Thanks a lot!
