### ISSUE TITLE
Support For Adding Plist file

### ISSUE THREAD

**Issue by ganesh-p** [xndrs/XReSign#21]
Hi,

  Very Good tool, Appreciations for it.  Will this tool support adding a plist file to an existing IPA, like googleservice-info.plist file. If so, pls. share the option.

Thanks,
Ganesh

**Comment by xndrs** [comment]
> Hi,
> 
> Very Good tool, Appreciations for it. Will this tool support adding a plist file to an existing IPA, like googleservice-info.plist file. If so, pls. share the option.
> 
> Thanks,
> Ganesh

Hi. No, I don't think. This is not a purpose of this tool.
