### ISSUE TITLE
Crash after XReSign FINISHED

### ISSUE THREAD

**Issue by lividus** [xndrs/XReSign#4]
Start resign the app...
Sign process using existing provisioning profile from payload
Extract entitlements from mobileprovisioning
Changing BundleID with : <bundle id>
Get list of components and resign with certificate: <certificate>
<path>: replacing existing signature
Creating the signed ipa
Clear temporary files
XReSign FINISHED

fatal error: unexpectedly found nil while unwrapping an Optional value
Current stack trace:
0    libswiftCore.dylib                 0x0000000100283ce0 swift_reportError + 132
1    libswiftCore.dylib                 0x00000001002a1090 _swift_stdlib_reportFatalError + 61
2    libswiftCore.dylib                 0x00000001000970c0 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
3    libswiftCore.dylib                 0x0000000100213230 partial apply for (_fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never).(closure #2) + 109
4    libswiftCore.dylib                 0x00000001000970c0 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
5    libswiftCore.dylib                 0x00000001001cb3f0 specialized _fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never + 96
6    XReSign                            0x000000010000cec0 ViewController.showAlertWith(title : String?, message : String, style : NSAlertStyle) -> () + 1105
7    XReSign                            0x0000000100009970 specialized ViewController.(signIpaWith(path : String, developer : String, provisioning : String, bundle : String?) -> ()).(closure #1).(closure #1) + 1045
8    XReSign                            0x0000000100003880 thunk + 39
9    libdispatch.dylib                  0x000000010092b064 _dispatch_call_block_and_release + 12
10   libdispatch.dylib                  0x000000010091dcbd _dispatch_client_callout + 8
11   libdispatch.dylib                  0x0000000100934b91 _dispatch_main_queue_callback_4CF + 2845
12   CoreFoundation                     0x00007fff8a6b9940 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
13   CoreFoundation                     0x00007fff8a678090 __CFRunLoopRun + 1949
14   CoreFoundation                     0x00007fff8a677d00 CFRunLoopRunSpecific + 296
15   HIToolbox                          0x00007fff96e2d84a RunCurrentEventLoopInMode + 235
16   HIToolbox                          0x00007fff96e2d5bf ReceiveNextEventCommon + 432
17   HIToolbox                          0x00007fff96e2d568 _BlockUntilNextEventMatchingListInModeWithFilter + 71
18   AppKit                             0x00007fff9004f9cb _DPSNextEvent + 1067
19   AppKit                             0x00007fff9004f060 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
20   AppKit                             0x00007fff90043ad6 -[NSApplication run] + 682
21   AppKit                             0x00007fff9000ced0 NSApplicationMain + 1176
22   XReSign                            0x000000010000fff0 main + 84
23   libdyld.dylib                      0x00007fff822f65ac start + 1
warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.

**Comment by xndrs** [comment]
There is no any dependency between the error and resign process
