### ISSUE TITLE
"Select a signing certificate" is blank

### ISSUE THREAD

**Issue by aananias** [xndrs/XReSign#5]
"Select a signing certificate" is blank. Certificate is confirmed and valid in key chain.

**Comment by xndrs** [comment]
> "Select a signing certificate" is blank. Certificate is confirmed and valid in key chain.

What's the flow? 
You select from drop down list required certificate, but it failed to insert into the "certificate" field ?
Which macOS version?

**Comment by aananias** [comment]
The problem might be on my end... I don't know. I use the Mac for remote
ssh compilation from a PC-based unreal engine platform. But certificates
are installed in the key chain properly, yet they don't show up in the drop
down list.
