### ISSUE TITLE
Ios 12

### ISSUE THREAD

**Issue by dvbguy** [xndrs/XReSign#6]
I re-sign the app with no errors. But when opening the file in IOS 12 devices it just open a second and closes without any notification. On ios 11 devices the same app works fine ?

**Comment by guadaran** [comment]
Hi @dvbguy ,

I used XReSign to sign severals apps and works fine with iOS 12

Do you tried with another app?
Do you used ideviceinstaller?

**Comment by dvbguy** [comment]
Actually right now we are only having this one app, so can not even test any developed ipa file with the certificate. But it is really strange it works for ios 11 devices but not 12, so cannot understand it can be a device signing issue
Ideviceinstaller I don´t  know ? is that an additionally tool
